### ISSUE TITLE
pytest_cov does not load first

### ISSUE THREAD

**Issue by hunse** [nengo/pytest-allclose#2]
This prevents coverage from being properly recorded for imports and function definitions.

**Comment by hunse** [comment]
According to [this](https://github.com/pytest-dev/pytest/issues/935), passing `-p pytest_cov` should load the plugin first. But it doesn't fix our coverage problem.

**Comment by drasmuss** [comment]
We decided we're hoping that this will be fixed by something upstream in pytest, but we probably won't have dev time to put into this any time soon.
